---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: business-processes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: business-processes
spec:
  project: default
  source:
    repoURL: 'https://github.com/ZedoMann05/k8s.git'
    path: business-processes
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: business-processes
  syncPolicy:
    syncOptions:
      - CreateNamespace=true