resources:
  - ./app
  - clusterissuer.yml

helmCharts:
  - name: camunda-platform
    releaseName: camunda
    repo: https://helm.camunda.io
    namespace: business-processes
    version: 10.2.1
    valuesFile: camunda-values.yml

  - name: flowable
    releaseName: flowable
    repo: https://flowable.github.io/helm/
    namespace: business-processes
    version: 7.0.1
    valuesFile: flowable-values.yml