apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-healthcheck
  template:
    metadata:
      labels:
        app: nginx-healthcheck
    spec:
      initContainers:
      - name: generate-auth
        image: busybox
        command: ['sh', '-c', 'echo -n "$AUTH_USER:$AUTH_PASS" | base64 > /auth/auth_basic']
        env:
        - name: AUTH_USER
          value: "admin"  # Задайте ім'я користувача
        - name: AUTH_PASS
          value: "test"   # Задайте пароль
        volumeMounts:
        - name: auth-volume
          mountPath: /auth
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: auth-volume
          mountPath: /etc/nginx/auth
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        env:
        - name: AUTH_BASIC
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: auth_basic
      volumes:
      - name: auth-volume
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-healthcheck-service
spec:
  selector:
    app: nginx-healthcheck
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen       80;
        
      location /actuator/health {
          proxy_pass http://flowable-flowable-ui:8080;
          proxy_set_header Authorization "Basic $AUTH_BASIC";
      }
    }
